precio_base=float(input("Precio base de la moto: "))
impuesto=float(input("Porcentaje de impuesto: "))
print("Suma (precio + impuesto)")
print(precio_base,"+",impuesto,precio_base+impuesto)
print("Resta (precio - descuento)")
print(precio_base,"-",impuesto,precio_base-impuesto)
print("Multiplicación (precio * cantidad)")
print(precio_base,"*",impuesto,precio_base*impuesto)
print("División (precio / cuotas)")
print(precio_base,"/",impuesto,precio_base/impuesto)
print("Módulo")
print(precio_base,"%",impuesto,precio_base%impuesto)
print("Exponentes (interés compuesto)")
print(precio_base,"**",impuesto,precio_base**impuesto)