print("Comparación de precios de motos")

precio_moto1=float(input("Precio moto 1: "))
precio_moto2=float(input("Precio moto 2: "))
print(precio_moto1,"==",precio_moto2,precio_moto1==precio_moto2)
print(precio_moto1,"!=",precio_moto2,precio_moto1!=precio_moto2)
print(precio_moto1,">",precio_moto2,precio_moto1>precio_moto2)
print(precio_moto1,"<",precio_moto2,precio_moto1<precio_moto2)
print(precio_moto1,">=",precio_moto2,precio_moto1>=precio_moto2)
print(precio_moto1,"<=",precio_moto2,precio_moto1<=precio_moto2)
print(numero1,">=",numero2,numero1>numero2)
print(numero1,"<=",numero2,numero1<numero2)